# Generated by Django 5.2.1 on 2025-06-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project_technologies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='level',
            new_name='proficiency',
        ),
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
